# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "keatonquizplusdelcatty16"

# Version of this mod.
version = "1.1.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Keaton Quiz Plus"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
Makes changes to the Keaton Quiz.

You can choose how fast Keaton will appear.
How many questions are required to receive the prize
Choose between the vanilla set of questions or alternative sets of questions based on Majora's Mask(Custom) and Ocarina of Time(OoT).
Option to change the color of the highlighted words during the quiz.
Option to toggle causing a Moon Crash upon getting a question wrong.


Thanks to LT_Schmiddy, ThatHypedPerson, magemods and Keanine for helping me various parts of the code!"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "Improvements to the Keaton Quiz!"

# Authors of this mod.
authors = [ "Delcatty16" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = ["MM_EZ_Text_Replacer_API:2.3.0"
# Example dependency:
#    "modname:1.0.0"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#   { name = "mm_recomp_mod_template_extlib", funcs = ["native_lib_test"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_recomp_keatonquizplusdelcatty16"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = [ "thumb.png" ]

# Info for building the extlib. If this mod will have no extlib, remove this section and
# the build scripts disable extlib compilation and packaging. You can then safely delete 
# ./CMakeLists.txt, ./CMakePresets.json, and ./src/extlib/**
# Mod config options
[[manifest.config_options]]
id = "QuestionSet"
name = "Question Set"
description = """
What types of questions will appear when taking part in the Keaton Quiz.

Vanilla - The original questions and answers from Majora's Mask.
Custom - A set of 30 additional questions based on Majora's Mask.
OoT - A set of 30 additional questions based on Ocarina of Time.
"""
type = "Enum"
options = [ "Vanilla", "Custom", "OoT" ]
default = "Custom"

[[manifest.config_options]]
id = "HighlightColour"
name = "Highlight Color"
description = """What color the highlighted words will be during the Keaton Quiz.
(Default is red)"""
type = "Enum"
options = [ "None", "Red", "Green", "Blue", "Yellow", "Cyan", "Pink", "Silver", "Orange" ]
default = "Red"

[[manifest.config_options]]
id = "KeatonQuizNumber"
name = "Number of Questions"
description = """How many questions Keaton will ask before rewarding you with the prize.
(Default is 5)"""
type = "Number"
min = 1
max = 30
step = 1
precision = 1
percent = false
default = 5

[[manifest.config_options]]
id = "KeatonAppearTimer"
name = "Keaton Appearance Speed"
description = """How long it takes in seconds for Keaton to appear after cutting the grass.
(Default is 6)"""
type = "Number"
min = 0
max = 6
step = 1
precision = 1
percent = false
default = 6

[[manifest.config_options]]
id = "CrashMoonOnFail"
name = "Moon Crash on Fail"
description = "Turning this on will cause the moon to crash and reset the cycle if you answer any question incorrectly."
type = "Enum"
options = [ "No", "Yes" ]
default = "No"